//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.NET_NHOM_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class BaiViet
    {
        public int MaBV { get; set; }
 
        [Required(ErrorMessage = "Không được để trống tiêu đề")]
        [DisplayName("Tiêu đề")]
        public string TieuDe { get; set; }
        
        [Required(ErrorMessage = "Không được để trống nội dung")]
        [DisplayName("Nội dung")]
        public string NoiDung { get; set; }
        
        [Required(ErrorMessage = "Không được để trống hình ảnh")]
        [DisplayName("Hình ảnh")]
        public string HinhAnh { get; set; }
        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        [DisplayName("Ngày sửa")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        [DisplayName("Người sửa")]
        public string ModifiedBy { get; set; }
        
    }
}
