//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.NET_NHOM_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }

        public KhachHang(string v, string v1)
        {
            HoaDons = new HashSet<HoaDon>();
        }

        public int ID { get; set; }

        [StringLength(250)]
        [Required(ErrorMessage = "Họ tên không được bỏ trống")]
        [DisplayName("Họ tên")]
        public string HoTen { get; set; }

        [DisplayName("Email")]
        [StringLength(250)]
        [Required(ErrorMessage = "Email không được bỏ trống")]
        public string Email { get; set; }

        [StringLength(250)]
        [Required(ErrorMessage = "Địa chỉ không được bỏ trống")]
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }

        [StringLength(10)]
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống")]
        [DisplayName("Số điện thoại")]
        public string SoDT { get; set; }

        [StringLength(250)]
        [Required(ErrorMessage = "Tên đăng nhập không được bỏ trống")]
        [DisplayName("Tên đăng nhập")]
        public string TenDangNhap { get; set; }
        [DisplayName("Mật khẩu")]
        [StringLength(250)]
        [Required(ErrorMessage = "Mật khẩu không được bỏ trống")]
       
        public string MatKhau { get; set; }

        [StringLength(250)]

        [DisplayName("Ảnh đại diện")]
        public string Avatar { get; set; }

       
        [DisplayName("Ngày tạo")]
        public DateTime? CreatedDate { get; set; }

        [StringLength(50)]
      
        [DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        
        [DisplayName("Ngày sửa")]
        public DateTime? ModifiedDate { get; set; }

        [StringLength(50)]
        [DisplayName("Người sửa")]
        public string ModifiedBy { get; set; }
        public string ResetPasswordCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
