//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.NET_NHOM_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaKM { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Tên KM")]
        public string TenKM { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Giảm giá")]
        public Nullable<double> Discount { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Người tạo")]
        public string CreatedBy { get; set; }
        [Required(ErrorMessage = "Bạn không được bỏ trống trường này")]
        [DisplayName("Ngày sửa")]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DisplayName("Người sửa")]
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
