//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_ASP.NET_NHOM_5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class QuanTri
    {
        public int ID { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Họ tên không được bỏ trống")]
        [DisplayName("Họ tên")]
        public string HoTen { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Địa chỉ không được bỏ trống")]
        [DisplayName("Địa chỉ")]
        public string DiaChi { get; set; }
        [StringLength(10)]
        [Required(ErrorMessage = "SDT không được bỏ trống")]
        [DisplayName("Số ĐT")]
        public string SoDT { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Username không được bỏ trống")]
        [DisplayName("UserName")]
        public string UserName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Password không được bỏ trống")]
        [DisplayName("Password")]
        public string Password { get; set; }
        public string Avatar { get; set; }
       
        [Required(ErrorMessage = "Không được bỏ trống trường này")]
        public Nullable<int> ChucVu { get; set; }
    }
}
